### ISSUE TITLE
Should be in django-polls to runserver.

### ISSUE THREAD

**Issue by gunnkrub** [kidstylex/django-polls#2]
not django-polls\mysite
It said:
```
(null): can't open file 'manage.py': [Errno 2] No such file or directory
```
if I were in django-polls\mysite

**Comment by bluaries** [comment]
Thank you for reminding me about this issue. Because of I refer to the directory ..\django-polls is ..\django\mysite on my computer. So you can runserver by go to `C:\Users\..\..\django-polls>py manage.py runserver` again.
